name: IntegrationTest
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}/${{ matrix.julia-version }}
    runs-on: ${{ matrix.os }}
    env:
      GROUP: ${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: [1,1.6]
        os: [ubuntu-latest]
        package:
                  - Components
          - Sol_Interface
          - MOL_Interface1
          - MOL_Interface2
          - Diffusion
          - Diffusion_NU
          - Nonlinear_Diffusion
          - Nonlinear_Diffusion_NU
          - 2D_Diffusion
          - Convection
          - Convection_WENO
          - Higher_Order
          - Stationary
          - DAE
          - Integrals
          - Burgers
          - Brusselator
          - Mixed_Derivatives
          - {user: SciML, repo: MethodOfLines.jl, group: Components}
          - {user: SciML, repo: MethodOfLines.jl, group: Sol_Interface}
          - {user: SciML, repo: MethodOfLines.jl, group: MOL_Interface1}
          - {user: SciML, repo: MethodOfLines.jl, group: MOL_Interface2}
          - {user: SciML, repo: MethodOfLines.jl, group: Diffusion}
          - {user: SciML, repo: MethodOfLines.jl, group: Diffusion_NU}
          - {user: SciML, repo: MethodOfLines.jl, group: Nonlinear_Diffusion}
          - {user: SciML, repo: MethodOfLines.jl, group: Nonlinear_Diffusion_NU}
          - {user: SciML, repo: MethodOfLines.jl, group: 2D_Diffusion}
          - {user: SciML, repo: MethodOfLines.jl, group: Convection}
          - {user: SciML, repo: MethodOfLines.jl, group: Convection_WENO}
          - {user: SciML, repo: MethodOfLines.jl, group: Higher_Order}
          - {user: SciML, repo: MethodOfLines.jl, group: Stationary}
          - {user: SciML, repo: MethodOfLines.jl, group: Integrals}
          - {user: SciML, repo: MethodOfLines.jl, group: Burgers}
          - {user: SciML, repo: MethodOfLines.jl, group: DAE}
          - {user: SciML, repo: PDESystemLibrary.jl, group: MOL}
          - {user: SciML, repo: NeuralPDE.jl, group: NNPDE1}
          - {user: SciML, repo: NeuralPDE.jl, group: NNPDE2}
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      - name: Clone Downstream
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.package.user }}/${{ matrix.package.repo }}
          path: downstream
      - name: Load this and run the downstream tests
        shell: julia --color=yes --project=downstream {0}
        run: |
          using Pkg
          try
            # force it to use this PR's version of the package
            Pkg.develop(PackageSpec(path="."))  # resolver may fail with main deps
            Pkg.update()
            Pkg.test(coverage=true)  # resolver may fail with test time deps
          catch err
            err isa Pkg.Resolve.ResolverError || rethrow()
            # If we can't resolve that means this is incompatible by SemVer and this is fine
            # It means we marked this as a breaking change, so we don't need to worry about
            # Mistakenly introducing a breaking change, as we have intentionally made one
            @info "Not compatible with this release. No problem." exception=err
            exit(0)  # Exit immediately, as a success
          end
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
